MoscowWeather/Models/ErrorViewModel.cs
namespace MoscowWeather.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MoscowWeather/ViewModels/ArchiveDetailsViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using MoscowWeather.Core.Models;

namespace MoscowWeather.ViewModels;

public class ArchiveDetailsViewModel
{
    public IReadOnlyList<Weather> Weathers { get; set; }
    public long Id { get; set; }
    public int PageCount { get; set; }
    public int CurrentPage { get; set; }
    public int StartPage { get; set; }
    public int EndPage { get; set; }
    public List<int> Months { get; set; }
    public List<int> SelectedYears { get; set; }
    public List<int> AvailableYears { get; set; }
}

MoscowWeather/ViewModels/IndexArchiveViewModel.cs
using MoscowWeather.Core.Models;

namespace MoscowWeather.ViewModels;

public class IndexArchiveViewModel
{
    public IReadOnlyList<WeatherArchive> Archives { get; set; }  
}

MoscowWeather/ViewModels/UploadDataViewModel.cs
namespace MoscowWeather.ViewModels;

public class UploadDataViewModel
{
    public List<IFormFile> Files { get; set; }
}

MoscowWeather/Controllers/ArchiveController.cs
using System.Diagnostics;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using MoscowWeather.Features.Archive;
using MoscowWeather.Features.Weather;
using MoscowWeather.ViewModels;

namespace MoscowWeather.Controllers;

public class ArchiveController : BaseController
{
    private readonly IMediator _mediator;

    public ArchiveController(IMediator mediator)
    {
        _mediator = mediator;
    }

    public async Task<IActionResult> Index()
    {
        var archives = await _mediator.Send(new GetArchivesQuery());
        var model = new IndexArchiveViewModel() { Archives = archives };
        Response.Headers.Add("Refresh", "5");
        return View(model);
    }

    public async Task<IActionResult> Delete(long id)
    {
        await _mediator.Send(new DeleteArchiveCommand() { ArchiveId = id});
        return Redirect("/");
    }
    
    public async Task<IActionResult> Details(long id, List<int> months, List<int> years, int count = 15, int page = 1)
    {
        var model = await _mediator.Send(new GetWeathersQuery() { ArchiveId = id, Count = count, Page = page, Months = months, Years = years});
        return View(model);
    }

    public async Task<IActionResult> Stop(long id)
    {
        await _mediator.Send(new StopParsingArchiveCommand() { ArchiveId = id });
        return Redirect("/");
    }
}

MoscowWeather/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;

namespace MoscowWeather.Controllers;

public class BaseController : Controller
{
    
}

MoscowWeather/Controllers/UploadController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using MoscowWeather.Features.Archive;
using MoscowWeather.ViewModels;

namespace MoscowWeather.Controllers;

public class UploadController : BaseController
{
    private readonly IMediator _mediator;

    public UploadController(IMediator mediator)
    {
        _mediator = mediator;
    }

    public IActionResult Index()
    {
        return View();
    }
    
    [HttpPost]
    public async Task<ViewResult> Index(UploadDataViewModel model)
    {
        try
        {
            var command = new UploadArchivesCommand() {Archives = model.Files};
            await _mediator.Send(command);   
            ViewBag.Message = "File Uploaded Successfully!!";
            return View();
        }
        catch
        {
            ViewBag.Message = "File upload failed!!";
            return View();
        }
    }
}

MoscowWeather/Views/Archive/Details.cshtml
@model MoscowWeather.ViewModels.ArchiveDetailsViewModel

@{
    ViewData["Title"] = "Погода в Москве";
}


<script>
$(document).ready(function(){
    $('#selectMonth').on('click', () => {
        const params = new URLSearchParams({
            page: @Model.CurrentPage,
        });
        
        let months = $('#months').val();
        months.map((x) => params.append('months', x));
        
        let years = $('#years').val();
        years.map((x) => params.append('years', x));
        
        const result = "@Model.Id?"+params.toString();
        window.location='/Archive/Details/'+result;
    });
});
</script>


<div class="flex">
    <select id="years" class="selectpicker" multiple>
        @foreach (var year in Model.AvailableYears)
        {
            <!option @(Model.SelectedYears.Contains(year) ? "selected" : "") value="@year">@year</!option>
        }
    </select>
    <select id="months" class="selectpicker" multiple>
        <!option @(Model.Months.Contains(1) ? "selected" : "") value="1">Январь</!option>
        <!option @(Model.Months.Contains(2) ? "selected" : "") value="2">Февраль</!option>
        <!option @(Model.Months.Contains(3) ? "selected" : "") value="3">Март</!option>
        <!option @(Model.Months.Contains(4) ? "selected" : "") value="4">Апрель</!option>
        <!option @(Model.Months.Contains(5) ? "selected" : "") value="5">Май</!option>
        <!option @(Model.Months.Contains(6) ? "selected" : "") value="6">Июнь</!option>
        <!option @(Model.Months.Contains(7) ? "selected" : "") value="7">Июль</!option>
        <!option @(Model.Months.Contains(8) ? "selected" : "") value="8">Август</!option>
        <!option @(Model.Months.Contains(9) ? "selected" : "") value="9">Сентябрь</!option>
        <!option @(Model.Months.Contains(10) ? "selected" : "") value="10">Октябрь</!option>
        <!option @(Model.Months.Contains(11) ? "selected" : "") value="11">Ноябрь</!option>
        <!option @(Model.Months.Contains(12) ? "selected" : "") value="12">Декабрь</!option>
    </select>
    <button id="selectMonth" class="btn btn-outline-dark" type="button">Отобразить</button>
</div>
@if (Model.Weathers.Count < 1)
{
    <div>Ничего не найдено по вашему запросу</div>
    return;
}
<table class="table mt-2">
    <thead>
    <tr>
        <th>ID</th>
        <th>Время</th>
        <th>Температура</th>
        <th>Отн. влажность воздуха (%)</th>
        <th>Точка росы</th>
        <th>Атм. давление,мм рт.ст.</th>
        <th>Направление ветра</th>
        <th>Скорость ветра, м/с</th>
        <th>Облачность, %</th>
        <th>Нижняя граница облачности</th>
        <th>Горизонтальная видимость, км</th>
        <th>Погодные явления</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Weathers)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTimeUtc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Temperature)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RelativeHumidity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DewPoint)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pressure)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WindDirection)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WindSpeed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cloudy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LowerCloudLimit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HorizontalVisibility)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WeatherConditions)
            </td>
        </tr>
    }
    </tbody>
</table>

@if (Model.PageCount == 0)
{
    return;
}

<nav class="mt-2">
    <ul class="pagination">
        @if (Model is { CurrentPage: > 9,PageCount: > 16 })
        {
            <li class="page-item">
                @Html.ActionLink(1.ToString(), "Details", new { page = 1, months = Model.Months }, new { @class = "page-link" })
            </li>
            <li class="page-item disabled">
                <a class="page-link">...</a>
            </li>
        }
        @for (var i = Model.StartPage; i <= Model.PageCount && i <= Model.EndPage; i++)
        {
            var disabled = Model.CurrentPage == i;
            @if (disabled)
            {
                <li class="page-item disabled">
                    @Html.ActionLink(i.ToString(), "Details", new { page = i, months = Model.Months }, new { @class = $@"page-link {disabled}" })
                </li>
            }
            else
            {
                <li class="page-item">
                    @Html.ActionLink(i.ToString(), "Details", new { page = i, months = Model.Months }, new { @class = $@"page-link {disabled}" })
                </li>
            }
        }
        @if (Model.StartPage + 15 < @Model.PageCount)
        {
            <li class="page-item disabled">
                <a class="page-link">...</a>
            </li>
            <li class="page-item">
                @Html.ActionLink(Model.PageCount.ToString(), "Details", new { page = Model.PageCount, months = Model.Months }, new { @class = "page-link" })
            </li>
        }

    </ul>
</nav>

MoscowWeather/Views/Archive/Index.cshtml
@using MoscowWeather.Core.Enums
@using NPOI.SS.Formula.Functions
@model MoscowWeather.ViewModels.IndexArchiveViewModel

@{
    ViewData["Title"] = "Архивы";
}

@if (Model.Archives.Count == 0)
{
    <div>Упс, не найдено. Загрузите архив!</div>
    return;
}

<table class="table">
    <thead>
    <tr>
        <th>
            ID
        </th>
        <th>
            Название
        </th>
        <th>
            Статус
        </th>
        <th>
            Дата загрузки
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Archives)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UploadedAt)
            </td>
            <td>
                @if (item.Status is ArchiveStatus.Ready)
                {
                    <a asp-controller="Archive" asp-action="Details" asp-route-id="@item.Id">Посмотреть</a>
                }
                @if (item.Status is not ArchiveStatus.InWork)
                {
                    <a asp-controller="Archive" asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
                }
                @if (item.Status is ArchiveStatus.InWork)
                {
                    <a asp-controller="Archive" asp-action="Stop" asp-route-id="@item.Id">Остановить</a>
                }
            </td>
        </tr>
    }
    </tbody>
</table>

MoscowWeather/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MoscowWeather</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/weather.css" asp-append-version="true"/>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Archive" asp-action="Index">MoscowWeather</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Archive" asp-action="Index">Архивы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Upload" asp-action="Index">Загрузить данные</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="new-container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - MoscowWeather by Alexander Chernykh
    </div>
</footer>
@* <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MoscowWeather/Views/Upload/Index.cshtml
@model MoscowWeather.ViewModels.UploadDataViewModel 

@{
    ViewData["Title"] = "Загрузка архива";
}


<div class="d-flex justify-content-center">
    <form enctype="multipart/form-data" method="post">
        <div class="input-group">
            <div class="custom-file">
                <label class="custom-file-label" asp-for="Files">Выбрать архивы</label>
                <input id="file-upload" type="file" class="custom-file-input" asp-for="Files" multiple="multiple">
            </div>
        </div>
        <div class="text-center mt-3">
            <input asp-page-handler="Upload" class="btn btn-outline-secondary btn-block" type="submit" value="Отправить"/>
        </div>
    </form>
</div>

<script>
$("#file-upload").change(function(){
  $(this).prev('label').text(Array.from(this.files).map(x => x.name));
});
</script>